{% set name = "feathr" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/feathr-{{ version }}.tar.gz
  sha256: 04951c3e0ce6c757323a5a667e2b9c790af7b0ca2e40f13543c13345b1f5ee37

build:
  entry_points:
    - feathr=feathrcli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - click <=8.1.3
    - py4j <=0.10.9.7
    - loguru <=0.6.0
    - pandas
    - redis-py <=4.4.0
    - requests <=2.28.1
    - tqdm <=4.64.1
    - pyapacheatlas <=0.14.0
    - pyhocon <=0.3.59
    - pandavro <=1.7.1
    - pyyaml <=6.0
    - jinja2 <=3.1.2
    - pyarrow <=9.0.0
    - pyspark >=3.1.2
    - python-snappy <=0.6.1
    - deltalake >=0.6.2
    - graphlib-backport <=1.0.3
    - protobuf <=3.19.4,>=3.0.0
    - python-confluent-kafka <=1.9.2
    - databricks-cli <=0.17.3
    - avro <=1.11.2
    - azure-storage-file-datalake <=12.5.0
    - azure-synapse-spark
    - aiohttp ==3.8.3
    - azure-identity >=1.8.0
    - azure-keyvault-secrets <=4.6.0
    - azure-core <=1.22.1
    - msrest <=0.6.21
    - typing-extensions >=4.2.0

test:
  imports:
    - feathr
    - feathrcli
  commands:
    - feathr --help
  requires:
    - pip

about:
  home: https://github.com/feathr-ai/feathr
  summary: An Enterprise-Grade, High Performance Feature Store
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706
